2023-10-17 15:27:33,082 INFO    MainThread:262613 [wandb_setup.py:_flush():76] Current SDK version is 0.15.12
2023-10-17 15:27:33,082 INFO    MainThread:262613 [wandb_setup.py:_flush():76] Configure stats pid to 262613
2023-10-17 15:27:33,082 INFO    MainThread:262613 [wandb_setup.py:_flush():76] Loading settings from /home/sjkim/.config/wandb/settings
2023-10-17 15:27:33,082 INFO    MainThread:262613 [wandb_setup.py:_flush():76] Loading settings from /home/sjkim/ICLR2023/wandb/settings
2023-10-17 15:27:33,082 INFO    MainThread:262613 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-10-17 15:27:33,082 INFO    MainThread:262613 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'train.py', 'program_abspath': '/home/sjkim/ICLR2023/train.py', 'program': '/home/sjkim/ICLR2023/train.py'}
2023-10-17 15:27:33,082 INFO    MainThread:262613 [wandb_init.py:_log_setup():528] Logging user logs to /home/sjkim/ICLR2023/outputs/2023-10-17/15-27-33/wandb/run-20231017_152733-clcwtnwb/logs/debug.log
2023-10-17 15:27:33,082 INFO    MainThread:262613 [wandb_init.py:_log_setup():529] Logging internal logs to /home/sjkim/ICLR2023/outputs/2023-10-17/15-27-33/wandb/run-20231017_152733-clcwtnwb/logs/debug-internal.log
2023-10-17 15:27:33,082 INFO    MainThread:262613 [wandb_init.py:init():568] calling init triggers
2023-10-17 15:27:33,082 INFO    MainThread:262613 [wandb_init.py:init():575] wandb.init called with sweep_config: {}
config: {'_metadata': ContainerMetadata(ref_type=typing.Any, object_type=<class 'dict'>, optional=True, key=None, flags={'struct': True}, flags_root=False, resolver_cache=defaultdict(<class 'dict'>, {'now': {('%Y-%m-%d',): '2023-10-17', ('%H-%M-%S',): '15-27-33'}}), key_type=typing.Any, element_type=typing.Any), '_parent': None, '_flags_cache': {'struct': True}, '_content': {'outer_policy_lr': 0.0001, 'outer_value_lr': 1e-05, 'inner_policy_lr': 0.001, 'inner_value_lr': 0.001, 'inner_buffer_size': -1, 'outer_buffer_size': -1, 'weight_transform': True, 'task_config': 'task_config/arc.json', 'advantage_head_coef': 0.001, 'net_width': 128, 'net_depth': 3, 'device': 'cuda', 'outer_batch_size': 4, 'inner_batch_size': 4, 'rollout_interval': 2500, 'model_save_interval': 2500, 'finetune_steps': 2500}}
2023-10-17 15:27:33,082 INFO    MainThread:262613 [wandb_init.py:init():618] starting backend
2023-10-17 15:27:33,082 INFO    MainThread:262613 [wandb_init.py:init():622] setting up manager
2023-10-17 15:27:33,083 INFO    MainThread:262613 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-10-17 15:27:33,083 INFO    MainThread:262613 [wandb_init.py:init():628] backend started and connected
2023-10-17 15:27:33,203 ERROR   MainThread:262613 [wandb_init.py:init():1198] error
Traceback (most recent call last):
  File "/home/sjkim/arcle_env/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1170, in init
    run = wi.init()
  File "/home/sjkim/arcle_env/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 633, in init
    run = Run(
  File "/home/sjkim/arcle_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 565, in __init__
    self._init(
  File "/home/sjkim/arcle_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 683, in _init
    self._config._update(config, ignore_locked=True)
  File "/home/sjkim/arcle_env/lib/python3.10/site-packages/wandb/sdk/wandb_config.py", line 177, in _update
    sanitized = self._sanitize_dict(
  File "/home/sjkim/arcle_env/lib/python3.10/site-packages/wandb/sdk/wandb_config.py", line 237, in _sanitize_dict
    k, v = self._sanitize(k, v, allow_val_change)
  File "/home/sjkim/arcle_env/lib/python3.10/site-packages/wandb/sdk/wandb_config.py", line 255, in _sanitize
    val = json_friendly_val(val)
  File "/home/sjkim/arcle_env/lib/python3.10/site-packages/wandb/util.py", line 671, in json_friendly_val
    converted = asdict(val)
  File "/home/sjkim/.pyenv/versions/3.10.12/lib/python3.10/dataclasses.py", line 1238, in asdict
    return _asdict_inner(obj, dict_factory)
  File "/home/sjkim/.pyenv/versions/3.10.12/lib/python3.10/dataclasses.py", line 1245, in _asdict_inner
    value = _asdict_inner(getattr(obj, f.name), dict_factory)
  File "/home/sjkim/.pyenv/versions/3.10.12/lib/python3.10/dataclasses.py", line 1275, in _asdict_inner
    return type(obj)((_asdict_inner(k, dict_factory),
TypeError: first argument must be callable or None
2023-10-17 15:27:34,313 WARNING MsgRouterThr:262613 [router.py:message_loop():77] message_loop has been closed
